### ISSUE TITLE
macos更新到Sequoia 15.1.1版本后启动DNS Server报错（FlyEnv 版本Version 4.5.6）

### ISSUE THREAD

**Issue by lfcheng92** [xpf0000/FlyEnv#149]
具体报错如下：
SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47

**Comment by Yuuuu9658** [comment]
用 FlyEnv 自带的端口工具看一下，是不是53端口被占用了，把端口kill掉就行

**Comment by lfcheng92** [comment]
> 用 FlyEnv 自带的端口工具看一下，是不是53端口被占用了，把端口kill掉就行

查了，没有被占用，启动还是报错。软件退出重启也一样。
<img width="652" alt="image" src="https://github.com/user-attachments/assets/657608d4-d8bb-4498-8b45-148905918d2b">

**Comment by imyellow** [comment]
53端口可以改吗，被Clash占用了
